### ISSUE TITLE
Support for JEI ≥ 10

### ISSUE THREAD

**Issue by traveldesign** [PssbleTrngle/BigSip#15]
### What happened?

Hi there, I love the mod so far. However, JEI only shows me the recipe for the grape sapling and the barrel. None of the drinks are showing. I dunno why. 

JEI Version is 10.1.3.240

### Mod Version

0.0.1-alpha

### Minecraft Version

1.18

### Fabric/Forge Version

40.1.68

**Comment by PssbleTrngle** [comment]
Pretty much the same thing as I mentioned in your other issue

**Comment by traveldesign** [comment]
You were right about the version. I downgraded and it fixed the problem.
Thanks!
