### ISSUE TITLE
Compat with Create: Alloyed

### ISSUE THREAD

**Issue by traveldesign** [PssbleTrngle/BigSip#17]
Hi there, I love the mod so much. Whenever I have Big Sip with Create: Alloyed, Big Sip crashes as the game starts. I would love to be able to play with both. 

Thanks!

**Comment by PssbleTrngle** [comment]
Can you send me a crash report?

**Comment by traveldesign** [comment]
Hmm I loaded the game up again and it works now. I have no idea why.

**Comment by PssbleTrngle** [comment]
Does it work reliably?

**Comment by traveldesign** [comment]
It seems to now! I’ll let you know if I run Into any issues.
