### ISSUE TITLE
Create 0.5.1 compat for 1.18.2 

### ISSUE THREAD

**Issue by FoxyFox909** [PssbleTrngle/BigSip#23]
### Describe the feature you have in mind.

Hello, I was just wondering if your lovely create add-ons, including Big Sip, Slice and Dice, and the jetpack one will receive a compatibility update for Create 0.5.1 for the version **1.18.2**?

I am making a 1.18.2 modpack, so I would like to know. This was the best place to ask that I could find.

Thank you!

**Comment by PssbleTrngle** [comment]
Create Slice & Dice and Jetpack will receive an update for create 0.5.1 on 1.18.2 very soon, Big Sip is right now a bit out of scope and it will probably take a while until I resume working on it, but it is not abandoned
