### ISSUE TITLE
Error while loading the mod

### ISSUE THREAD

**Issue by Sniffierpond** [PssbleTrngle/BigSip#24]
### What happened?

Minecraft Forge got some errors while attempting to load the mod. Here's a screenshot:
![image](https://github.com/PssbleTrngle/BigSip/assets/77970453/0e74462e-3f24-469e-9671-6de560e63b3a)
And here's the crash report:
[crash-2023-09-13_21.53.28-fml.txt](https://github.com/PssbleTrngle/BigSip/files/12601451/crash-2023-09-13_21.53.28-fml.txt)
and the latest.log:
[latest.log](https://github.com/PssbleTrngle/BigSip/files/12601484/latest.log)

### Mod Version

0.0.3-alpha

### Minecraft Version

None

### Minecraft Loader

None

### Fabric/Forge Version

40.2.10

**Comment by PssbleTrngle** [comment]
Which create version are you using?

**Comment by Sniffierpond** [comment]
I currently don't have access to my computer but I think I downloaded the last 1.18.2 create version, 1.18.2-0.5.1.c.

**Comment by PssbleTrngle** [comment]
Oh that makes sense, the mod does not support the latest create versions, because it's only in alpha and has not been updated for a while, sorry.
I really hope I'll have some time in the future to work on it again :/

**Comment by Sniffierpond** [comment]
Oh I didn't know sorry.
